---
title: "Exam 1"
format: html
code-fold: true
---

```{r}
# load packages
library(tidytuesdayR)
library(tidyverse)

# get data
tuesdata <- tt_load('2020-02-18')
food_consumption <- tuesdata[["food_consumption"]]

```

## Total Consumption by Country

```{r}
#| fig-width: 10
#| fig-alt: "Column graph showing total consumption of all food categories by top ten highest-consuming countries. Finland has the highest consumption of approximately 630, and the others are between about 500 and 550. Data from Tidy Tuesday, https://github.com/rfordatascience/tidytuesday/tree/main/data/2020/2020-02-18."
#| fig-cap: "Column graph showing total consumption of all food categories by top ten highest-consuming countries. Data from Tidy Tuesday, https://github.com/rfordatascience/tidytuesday/tree/main/data/2020/2020-02-18."

# total consumption by country
food_consumption |>
  group_by(country) |>
  summarise(total_consumption = sum(consumption)) |>
  arrange(desc(total_consumption)) |>
  head(10) |>
  ggplot(aes(x = country, y = total_consumption, fill = country)) +
  geom_col() +
  theme()

```

## Total Consumption by Food Category

```{r}
#| fig-width: 10
#| fig-alt: "Column graph comparing total consumption across all countries by the top 10 most-consumed food categories. The category with the highest consumption was milk including cheese and the lowest was lamb and goat. Data from Tidy Tuesday, https://github.com/rfordatascience/tidytuesday/tree/main/data/2020/2020-02-18."
#| fig-cap: "Column graph comparing total consumption across all countries by the top 10 most-consumed food categories. Data from Tidy Tuesday, https://github.com/rfordatascience/tidytuesday/tree/main/data/2020/2020-02-18."

# total consumption by food category
food_consumption |>
  group_by(food_category) |>
  summarise(total_consumption = sum(consumption)) |>
  arrange(desc(total_consumption)) |>
  head(10) |>
  ggplot(aes(x = food_category, y = total_consumption, fill = food_category)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 30))

```

## Grand Research Question

What does the consumption of each food category in each country look like? 

```{r}
#| fig-height: 25
#| fig-width: 45

food_consumption |>
  select(-co2_emmission) |>
  group_by(country) |>
  ggplot(aes(x = country, y = consumption, fill = food_category)) +
  geom_col() +
  labs(x = "Country", y = "Consumption", fill = "Food Category") +
  theme(axis.text.x = element_text(angle = 80, size = 24), 
        axis.title.x = element_text(size = 40),
        axis.text.y = element_text(size = 24),
        axis.title.y = element_text(size = 40),
        legend.position = "bottom", 
        legend.text = element_text(size = 36), 
        legend.title = element_text(size = 40), 
        legend.title.position = "left") +
  scale_fill_viridis_d()
```


